<?php

/**
 * @file
 * Contains d_paragraphs.module..
 */

use Drupal\Core\StreamWrapper\PrivateStream;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_preprocess_HOOK().
 */
function d_p_subscribe_file_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  $bundle = $paragraph->bundle();

  $styles_ids = d_p_responsive_style_ids();

  switch ($bundle) {

    case 'd_p_subscribe_file':
      $styles_ids[] = 'responsive_image_768_banner';
      d_p_generate_image_set($variables, $styles_ids, $bundle);
      $variables['#attached']['library'][] = 'd_p_subscribe_file/d_p_subscribe_file';
      $form = \Drupal::formBuilder()
        ->getForm('Drupal\d_p_subscribe_file\Forms\SubscribeFileForm', $paragraph);
      $variables['additional_info'] = $variables['content']['field_d_p_sf_additional_info'];
      unset($variables['content']['field_d_p_sf_additional_info']);
      $variables['subscribe_file_form'] = $form;

      break;
  }
}


/**
 * Implements hook_theme().
 */
function d_p_subscribe_file_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__d_p_subscribe_file' => [
      'base hook' => 'paragraph',
    ],
    'download_page' => [
      'variables' => ['link' => NULL, 'title' => NULL, 'body' => NULL],
      'template' => 'd_p_subscribe_file_download_page',
    ],
    'subscribe_file_mail' => [
      'variables' => [
        'values' => NULL,
        'template' => 'd_p_subscribe_file_mail',
      ],
    ],
  ];
}

/**
 * Implements hook_requirements.
 */
function d_p_subscribe_file_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $private_path = PrivateStream::basePath();
    if ($private_path) {
      $requirements['droopler'] = array(
        'title' => t('droopler paragraphs'),
        'value' => t('Private file system path is set'),
        'severity' => REQUIREMENT_INFO
      );
    }
    else {
      $requirements['droopler'] = array(
        'title' => t('droopler paragraphs'),
        'value' => t('Private file system path is not set'),
        'severity' => REQUIREMENT_ERROR,
        'description' => t('You need set Private file system path. <a href=":prv-file">How to set the private files directory</a>.', [':prv-file' => 'https://www.drupal.org/node/2392959']),
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_mail.
 */
function d_p_subscribe_file_mail($key, &$message, $params) {
  switch ($key) {
    case 'subscribe_form':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('@name, Droopler Download Link', array('@name' => $params['name']));
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $rendered = \Drupal::service('renderer')->render($params['body']);
      $message['body'][0] = \Drupal\Core\Render\Markup::create($rendered);
      break;
  }
}
